//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Stas_bdEntities2 : DbContext
    {
        private static Stas_bdEntities2 _context;
        public Stas_bdEntities2()
            : base("name=Stas_bdEntities2")
        {
        }
        public static Stas_bdEntities2 GetContext()
        {
            if (_context == null)
                _context = new Stas_bdEntities2();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<автомобиль> автомобиль { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Комплектация1> Комплектация1 { get; set; }
        public virtual DbSet<Менеджер> Менеджер { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Продажа> Продажа { get; set; }
        public virtual DbSet<Форма_Оплаты> Форма_Оплаты { get; set; }
    }
}
