//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Stas_bdEntities : DbContext
    {
        public Stas_bdEntities()
            : base("name=Stas_bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<автомобиль> автомобиль { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Комплектация1> Комплектация1 { get; set; }
        public virtual DbSet<Менеджер> Менеджер { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Продажа> Продажа { get; set; }
        public virtual DbSet<Форма_Оплаты> Форма_Оплаты { get; set; }
    }
}
