//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class автомобиль
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public автомобиль()
        {
            this.Продажа = new HashSet<Продажа>();
        }
    
        public int Код_Автомобиля { get; set; }
        public Nullable<int> Код_поставщика { get; set; }
        public string Марка_автомобиля { get; set; }
        public string Модель_автомобиля { get; set; }
        public string Кузов { get; set; }
        public Nullable<System.DateTime> Дата_выпуска { get; set; }
        public Nullable<bool> Наличие { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<decimal> цена { get; set; }
    
        public virtual Комплектация1 Комплектация1 { get; set; }
        public virtual Поставщик Поставщик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажа> Продажа { get; set; }
    }
}
