//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продажа()
        {
            this.Форма_Оплаты = new HashSet<Форма_Оплаты>();
        }
    
        public int Код_продажи { get; set; }
        public Nullable<int> Код_Автомобиля { get; set; }
        public Nullable<int> Код_менеджер { get; set; }
        public Nullable<int> Код_клиент { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
        public Nullable<decimal> Оплата { get; set; }
    
        public virtual автомобиль автомобиль { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Менеджер Менеджер { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Форма_Оплаты> Форма_Оплаты { get; set; }
    }
}
